// ignore_for_file: deprecated_member_use

import 'package:task/core/constants/dimens.dart';
import 'package:task/core/extensions/extensions.dart';

class ClassicTheme {
  static ThemeData get dark => _theme(
        colorScheme: const ColorScheme(
          brightness: Brightness.dark,
          primary: Color(0xffffb5a0),
          surfaceTint: Color(0xffffb5a0),
          onPrimary: Color(0xff561f0f),
          primaryContainer: Color(0xff723523),
          onPrimaryContainer: Color(0xffffdbd1),
          secondary: Color(0xffe7bdb2),
          onSecondary: Color(0xff442a22),
          secondaryContainer: Color(0xff5d4037),
          onSecondaryContainer: Color(0xffffdbd1),
          tertiary: Color(0xffd8c58d),
          onTertiary: Color(0xff3b2f05),
          tertiaryContainer: Color(0xff534619),
          onTertiaryContainer: Color(0xfff5e1a7),
          error: Color(0xffffb4ab),
          onError: Color(0xff690005),
          errorContainer: Color(0xff93000a),
          onErrorContainer: Color(0xffffdad6),
          surface: Color(0xff1a110f),
          onSurface: Color(0xfff1dfda),
          onSurfaceVariant: Color(0xffd8c2bc),
          outline: Color(0xffa08c87),
          outlineVariant: Color(0xff53433f),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xfff1dfda),
          inversePrimary: Color(0xff8f4c38),
          primaryFixed: Color(0xffffdbd1),
          onPrimaryFixed: Color(0xff3a0b01),
          primaryFixedDim: Color(0xffffb5a0),
          onPrimaryFixedVariant: Color(0xff723523),
          secondaryFixed: Color(0xffffdbd1),
          onSecondaryFixed: Color(0xff2c150f),
          secondaryFixedDim: Color(0xffe7bdb2),
          onSecondaryFixedVariant: Color(0xff5d4037),
          tertiaryFixed: Color(0xfff5e1a7),
          onTertiaryFixed: Color(0xff231b00),
          tertiaryFixedDim: Color(0xffd8c58d),
          onTertiaryFixedVariant: Color(0xff534619),
          surfaceDim: Color(0xff1a110f),
          surfaceBright: Color(0xff423734),
          surfaceContainerLowest: Color(0xff140c0a),
          surfaceContainerLow: Color(0xff231917),
          surfaceContainer: Color(0xff271d1b),
          surfaceContainerHigh: Color(0xff322825),
          surfaceContainerHighest: Color(0xff3d322f),
        ),
      );
  static ThemeData get light => _theme(
        colorScheme: const ColorScheme(
          brightness: Brightness.light,
          primary: Color(0xff8f4c38),
          surfaceTint: Color(0xff8f4c38),
          onPrimary: Color(0xffffffff),
          primaryContainer: Color(0xffffdbd1),
          onPrimaryContainer: Color(0xff3a0b01),
          secondary: Color(0xff77574e),
          onSecondary: Color(0xffffffff),
          secondaryContainer: Color(0xffffdbd1),
          onSecondaryContainer: Color(0xff2c150f),
          tertiary: Color(0xff6c5d2f),
          onTertiary: Color(0xffffffff),
          tertiaryContainer: Color(0xfff5e1a7),
          onTertiaryContainer: Color(0xff231b00),
          error: Color(0xffba1a1a),
          onError: Color(0xffffffff),
          errorContainer: Color(0xffffdad6),
          onErrorContainer: Color(0xff410002),
          surface: Color(0xfffff8f6),
          onSurface: Color(0xff231917),
          onSurfaceVariant: Color(0xff53433f),
          outline: Color(0xff85736e),
          outlineVariant: Color(0xffd8c2bc),
          shadow: Color(0xff000000),
          scrim: Color(0xff000000),
          inverseSurface: Color(0xff392e2b),
          inversePrimary: Color(0xffffb5a0),
          primaryFixed: Color(0xffffdbd1),
          onPrimaryFixed: Color(0xff3a0b01),
          primaryFixedDim: Color(0xffffb5a0),
          onPrimaryFixedVariant: Color(0xff723523),
          secondaryFixed: Color(0xffffdbd1),
          onSecondaryFixed: Color(0xff2c150f),
          secondaryFixedDim: Color(0xffe7bdb2),
          onSecondaryFixedVariant: Color(0xff5d4037),
          tertiaryFixed: Color(0xfff5e1a7),
          onTertiaryFixed: Color(0xff231b00),
          tertiaryFixedDim: Color(0xffd8c58d),
          onTertiaryFixedVariant: Color(0xff534619),
          surfaceDim: Color(0xffe8d6d2),
          surfaceBright: Color(0xfffff8f6),
          surfaceContainerLowest: Color(0xffffffff),
          surfaceContainerLow: Color(0xfffff1ed),
          surfaceContainer: Color(0xfffceae5),
          surfaceContainerHigh: Color(0xfff7e4e0),
          surfaceContainerHighest: Color(0xfff1dfda),
        ),
      );

  static ThemeData _theme({required ColorScheme colorScheme}) => ThemeData(
        visualDensity: VisualDensity.adaptivePlatformDensity,
        useMaterial3: true,
        primaryColor: colorScheme.primary,
        primaryColorDark: colorScheme.primary.withOpacity(.2),
        primaryColorLight: colorScheme.primary.withOpacity(.2),
        fontFamily: 'Poppins',
        bottomAppBarTheme: const BottomAppBarTheme(
            elevation: 0, shape: CircularNotchedRectangle(), height: 50),
        iconTheme:
            IconThemeData(color: colorScheme.primary.withOpacity(1), size: 26),
        colorScheme: colorScheme,
        inputDecorationTheme: InputDecorationTheme(
          isDense: true,
          filled: true,
          fillColor: colorScheme.secondary,
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
          disabledBackgroundColor: colorScheme.primary.withOpacity(.25),
          disabledForegroundColor: colorScheme.onPrimary,
          backgroundColor: colorScheme.primary,
          foregroundColor: colorScheme.onPrimary,
          shape: RoundedRectangleBorder(
              borderRadius: Dimens.radiusButton.toBorderRadius()),
          elevation: 0,
        )),
        listTileTheme: ListTileThemeData(
            shape: RoundedRectangleBorder(
                borderRadius: Dimens.radiusTile.toBorderRadius())),
        drawerTheme: DrawerThemeData(
            backgroundColor: colorScheme.surface,
            elevation: 0,
            surfaceTintColor: colorScheme.surface),
        cardTheme: CardTheme(color: colorScheme.secondary, elevation: 0),
        textTheme: _textTheme(colorScheme),
        appBarTheme: AppBarTheme(
          backgroundColor: colorScheme.primary,
          elevation: 0,
          titleTextStyle: TextStyle(color: colorScheme.onPrimary, fontSize: 22),
          iconTheme: IconThemeData(color: colorScheme.onPrimary, size: 22),
          toolbarHeight: 75,
          centerTitle: true,
        ),
      );

  static TextTheme _textTheme(ColorScheme colorScheme) => TextTheme(
        displayLarge: TextStyle(color: colorScheme.onSurface),
        displayMedium: TextStyle(color: colorScheme.onSurface),
        displaySmall: TextStyle(color: colorScheme.onSurface),
        headlineLarge: TextStyle(color: colorScheme.onSurface),
        headlineMedium: TextStyle(color: colorScheme.onSurface),
        headlineSmall: TextStyle(color: colorScheme.onSurface),
        titleLarge: TextStyle(color: colorScheme.onSurface),
        titleMedium: TextStyle(color: colorScheme.onSurface),
        titleSmall: TextStyle(color: colorScheme.onSurface),
        bodyLarge: TextStyle(color: colorScheme.onSurface),
        bodyMedium: TextStyle(color: colorScheme.onSurface),
        bodySmall: TextStyle(color: colorScheme.onSurface),
      );
}
